### ISSUE TITLE
version 1

### ISSUE THREAD

**Issue by JANEqiujie** [JANEqiujie/2023EBU6305G15#5]
Vision 1 features:

1.	It has home page, which has beautiful background and simple introduction. Also, there are links to weather and map.
2.	It has news page, which shows pictures and words of latest news.
3.	It has travel page, which has hover effect when you choose one picture. It can be linked into child pages in next version.
4.	It has business page, which has hover effect when you choose one picture. It can be linked into child pages in next version.
5.	It has opportunity page, which has hover effect when you choose one picture. It can be linked into child pages in next version.
6.	It has about us page. It contains the information of the web owner and has animation effect.
7.	It has foot page. It contains all the links in our website.
8.	The shift between home page, news page, travel page, business page, opportunity page are smoothly designed and displayed in the same window.
<img width="960" alt="屏幕截图 2023-04-07 230357" src="https://user-images.githubusercontent.com/79309743/230633841-dead759a-ef70-496f-9f17-49c8d6ec6302.png">
<img width="960" alt="屏幕截图 2023-04-07 230537" src="https://user-images.githubusercontent.com/79309743/230633863-02abd2c9-506b-4972-8b1a-ccba56efb27d.png">
<img width="960" alt="屏幕截图 2023-04-07 230613" src="https://user-images.githubusercontent.com/79309743/230633871-514c10ed-67a4-4f31-8e90-0a35b99f7ca9.png">
<img width="960" alt="屏幕截图 2023-04-07 230640" src="https://user-images.githubusercontent.com/79309743/230633877-b8884346-90cf-4705-90a6-394fd7c86996.png">
<img width="960" alt="屏幕截图 2023-04-07 231135" src="https://user-images.githubusercontent.com/79309743/230633879-4222c3d6-0a98-4a71-ab8a-56b70792456f.png">
<img width="960" alt="屏幕截图 2023-04-07 230436" src="https://user-images.githubusercontent.com/79309743/230633883-d0807382-751c-4f77-bd4f-880634efa333.png">
<img width="960" alt="屏幕截图 2023-04-07 230456" src="https://user-images.githubusercontent.com/79309743/230633885-edee995a-67d5-432e-a2c0-d6611fcf77f7.png">

**Comment by JANEqiujie** [comment]
Jie Qiu's work in v1:
1.Create the opportunity page and add pictures and hover effects. Write short introduction for each points. Find background picture and choose colors in design.
2.Create the left navigation bar and connect the pages together with smooth effect.
3. Joint our code together and debug.
4. Change the features of wireframe to v1 for better coding and display.
5. Organize group meeting, work division, DDLs, collect members' idea while coding.

**Comment by zxzzz525** [comment]
Xu Zhang's work in version1:
1. Design homepage. Collect beautiful pictures of scenic spots in Zhuhai as the background of web pages.
2. Design global fonts for web pages.
3. Design hypertext link effects.
4. Design the official website theme style.
5. Introduce two buttons to jump to other interfaces.
6. Design the small window avatar of Zhuhai

**Comment by 2020213120** [comment]
Yini Yang’s work in v1:
1.Create the news page and add pictures and introductive content. Make a short introduction for each points and add some hyperlink to connect. 
2.Choose a right background picture and choose the fine colors and word size in design.
3.Fit my codes with others and simplify them.
4. Creat hover effects to make the pictures look more attractive.
5.Participants and make give advice to every choice of our website and brainstorm new concepts to our design.
