### ISSUE TITLE
V2 contribute

### ISSUE THREAD

**Issue by zxzzz525** [JANEqiujie/2023EBU6305G15#6]
XuZhang' job in V2
1. Unified naming format
2. Made breadcrumb navigation
3. Made "Previous page", "Next page" and "Back screen" buttons
4. Collected materials and made three sub-interfaces of the "Business" section
5. Materials were collected and three sub-interfaces of the "Humanities" section were made
6. Materials were collected and three sub-interfaces of the "Humanities" section were made
7. Store all resources in the cloud

**Comment by JANEqiujie** [comment]
Jie Qiu's job in v2
1.Create 4 child pages which are livable environment, attractions, food, location.
2.Write short and attractive words about the topic.
3.Chose beautiful pictures as background.
4.Design the movement of the big heading.
5.Organize the group and distribute the work.
